[package]
name = "futures-compat"
version = "0.0.0"
description = "A compatibility layer between different versions of Future."
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
futures = "0.1"
futures-core = "0.2"

